name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - jupyter
  - pytest
  - nbconvert
  # Add other dependencies here, for Conda packages.
  - pip:
      # Pip-only packages here, if any.
      - qiskit[visualization]
      - qiskit-ionq
      - cirq
      - cirq-ionq
      - pennylane
      - pennylane-ionq
      - projectq
      - cudaq
      - pylatexenc
      - requests
      - ipykernel
